### ISSUE TITLE
canSkipRowEvents setting

### ISSUE THREAD

**Issue by wj32** [numtel/mysql-live-select#16]
(Thanks for merging in my changes last week! We've been running version 0.0.24 successfully since then and performance has improved drastically.)

In commit a44c86b the canSkipRowEvents setting seems to have been removed. Could you add it back?

Some background: It's my fault for not documenting this setting properly, but basically we rely on this setting being false so that matchRowEvent always calls our condition function for every single row event, rather than skipping events when the query cache's updateTimeout is null. We need this behavior because we have many large JOIN-based queries and we wrote condition functions that cache certain keys to filter out irrelevant row events. I added the canSkipRowEvents setting because most people don't need this behavior, and the updateTimeout === null check could improve performance if matchRowEvent is expensive.

**Comment by numtel** [comment]
Ah now I understand what that was for. With all the negations around it and in its name I had no clue to its purpose.

I have decided to rename it to `checkConditionWhenQueued`. I think this is a more descriptive name. Set that to `true` in order to make sure that all row events are passed to the condition functions.

A new version has been released.

**Comment by wj32** [comment]
Awesome, thanks a lot!
